### ISSUE TITLE
about custom dataset

### ISSUE THREAD

**Issue by vulyon** [limbo0000/InstanceLoc#8]
Hi,Sir. How to use custom Dataset? For example,how to modify the config  for the VOCDataset.

**Comment by limbo0000** [comment]
Hi @kwuliang , thanks for your question. 

I am not sure that you want the cfg of pretraining the model on VOC or say finetuning the trained model on VOC detection. If pretraining, just prepare a txt file containing the filenames of the whole set and modify the data path in the cfg. Otherwise, you could refer to the cfg in [MoCo](https://github.com/facebookresearch/moco/tree/master/detection) to finetune the trained models.

**Comment by vulyon** [comment]
I am confused about how to train InstanceLoc with my dataset. The type of mine is VOC. So Should I rewrite the Dataset(ImageNetDataset)? or how can I modify the condfig? em,The struct of my dataset is bellow:

|VOC2007
├── Annotations 进行 detection 任务时的标签文件，xml 形式，文件名与图片名一一对应
├── ImageSets 包含子文件夹 Main，其中 Main 存放检测的数据集分割文件
├── JPEGImages 存放 .jpg 格式的图片文件


├── Main
│   ├── train.txt 写着用于训练的图片名称， 
│   ├── val.txt 写着用于验证的图片名称，
│   ├── trainval.txt train与val的合集。
│   ├── test.txt 写着用于测试的图片名称，

**Comment by vulyon** [comment]
Could you prTraceback (most recent call last):
  File "./tools/train.py", line 204, in <module>
    main()
  File "./tools/train.py", line 192, in main
    meta=meta)
  File "/home/wuliang/cvprojects/InstanceLoc/mmdet/apis/train.py", line 111, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/wuliang/cvprojects/InstanceLoc/mmdet/models/detectors/base.py", line 202, in train_step
    losses = self(**data)
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wuliang/cvprojects/InstanceLoc/mmdet/models/detectors/base.py", line 137, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/wuliang/cvprojects/InstanceLoc/mmdet/models/detectors/insloc_fpn.py", line 309, in forward_train
    gt_bboxes_k if shuffle_bbox else None)
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/wuliang/cvprojects/InstanceLoc/mmdet/models/detectors/insloc_fpn.py", line 409, in _batch_shuffle_ddp
    x_gather = concat_all_gather(x)
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/wuliang/cvprojects/InstanceLoc/mmdet/models/detectors/insloc_fpn.py", line 24, in concat_all_gather
    for _ in range(torch.distributed.get_world_size())
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 620, in get_world_size
    return _get_group_size(group)
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 219, in _get_group_size
    _check_default_pg()
  File "/home/wuliang/anaconda3/envs/mmdetec2/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 210, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
ovide

**Comment by limbo0000** [comment]
I think you could use the train.txt which contains the filenames.

**Comment by vulyon** [comment]
thanks
